### ISSUE TITLE
Racket v8.8 release notes

### ISSUE THREAD

**Issue by jbclements** [reflektoin/dellu#3]
Please pardon this absurd use of github issues to get in touch with you....

I'm writing to thank you for contributing to the Racket v8.8 release, and to ask you how you'd like your name to appear in the release notes. Right now I have this:

reflektoin

Does that look reasonable? Please let me know!

John Clements (clements@racket-lang.org)

**Comment by reflektoin** [comment]
Yes, reflektoin is good.
Thank you for including me in the release notes.
And thank you for your work on Racket!
